name: common-ci

on:
  workflow_call:
    inputs:
      artifactoryServerId:
        type: string
        required: true
        description: 'Artifactory Server Id (typically from vars.JF_SERVER_ID)'
    secrets:
      JF_ARTIFACTORY_SPRING:

env:
  ARTIFACTORY_KEY: ${{ secrets.JF_ARTIFACTORY_SPRING }}
  ARTIFACTORY_SERVER_ID: ${{ inputs.artifactoryServerId }}

jobs:
  build_publish_scan:
    name: Build / Publish / Scan
    if: github.repository_owner == 'spring-cloud'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: 'https://repo.spring.io'
          JF_ENV_SPRING: ${{ env.ARTIFACTORY_KEY }}
        # setup frog cli
      - name: Configure JFrog Cli
        run: |
          jfrog mvnc --use-wrapper \
          --server-id-deploy=${{ env.ARTIFACTORY_SERVER_ID }} \
          --repo-deploy-releases=libs-release-local \
          --repo-deploy-snapshots=libs-snapshot-local
          echo JFROG_CLI_BUILD_NAME=spring-cloud-deployer-main >> $GITHUB_ENV
          echo JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV
      - name: Build and Publish
        run: |
          jfrog mvn -U -B -s .settings.xml clean install -T 0.5C
          jfrog rt build-publish
      - name: Scan
        uses: ./.github/actions/trivy-scan
        if: always()
